# Setup
title:            TH-MUNI
tagline:          'A Jekyll theme'
description:      'Master's student - Masaryk university.'
url:              http://truonghuynhmuni.github.io

author:
  name:           'Phuoc Truong Huynh'
  url:

relative_links:
  enabled: true
  collections: true
  include:
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
    - COPYING.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
