# Setup
title:            Mathematics
description:      'Mathematics and friends'
url:              truonghuynhmuni.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

relative_links:
  enabled: true
  collections: true
  include:
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
    - COPYING.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
